'use strict';

const crypto = require('crypto');
const CareerProfile = require('../models/careerProfile.model');
const ResumeConfiguration = require('../models/resumeConfiguration.model');
const ResumeTemplate = require('../models/resumeTemplate.model');
const Document = require('../models/document.model');
const aggregation = require('./careerProfileAggregation.service');
const composer = require('./resumeComposer.service');
const entitlementService = require('./entitlement.service');
const { buildDocumentModel } = require('../engine/buildDocumentModel');
const rendererRegistry = require('../engine/rendererRegistry');
const { saveBuffer } = require('./storage.service');
const AppError = require('../utils/AppError');
const { HTTP_STATUS } = require('../constants/httpStatus');
const { AUTH_MESSAGES } = require('../constants/messages');

// Orchestration only: load -> composer.resolveContent() -> engine.build ->
// engine.render() -> storage -> Document record. The engine itself (and the
// composer) know nothing about MongoDB/Express; this is the one layer that
// bridges them.
//
// KNOWN LIMITATION (not solved in this pass): document.service.js's
// getResume(userId) assumes a single active 'resume' Document per user. Once
// a user has multiple named ResumeConfigurations, each can have its own
// active generated Document simultaneously (by design — see
// architecture doc A7) — getResume() becomes ambiguous about "the" resume.
// Only THIS resumeConfiguration's previous generated Document is archived
// below (never another named resume's), so that part is correct; picking
// "the right resume" for a job application is a product decision for a
// later pass (e.g. always ask, or suggest by title match), not this one.
//
// Already-submitted Applications are deliberately NOT touched here. An earlier
// version of this service re-pointed each Application's 'resume' snapshot at
// the freshly generated document, so a recruiter always saw the applicant's
// current resume — but that also meant the applicant could silently change
// what an employer had already received, days after applying. The snapshot
// taken in applyToJob is now immutable for the life of the application: it
// keeps pointing at the exact Document that was sent, and that Document (plus
// its file) is preserved even after the user archives or regenerates it — see
// document.service.js's getAdminDocumentFile. Admins still see staleness, via
// the live `documentCompleteness` figure computed in application.service.js.

// Exported so resumeConfiguration.service.js can hash freshly-resolved content
// the same way and tell whether a generated PDF has since gone stale. Both
// sides MUST use this one function — a second implementation that hashed the
// same data differently would mark every resume permanently out of date.
const contentHash = (content, templateId) =>
  crypto.createHash('sha256').update(JSON.stringify({ content, templateId })).digest('hex');

// ── Free-tier watermark ─────────────────────────────────────────────────────
// Applied to every page of every resume generated by a user without a live
// subscription. The wording is fixed here, in code, on purpose: it is NOT a
// template field and NOT a request field, so no template an admin authors and
// no payload a client sends can weaken or remove it.
// Two layers, both fixed here in code and NOT derived from the template
// palette — a template must not be able to make the watermark disappear by
// matching it to its own background.
//
//  • A tiled, rotated wordmark across the whole page. Tiled rather than one
//    big diagonal because a single mark can be cropped or patched out, reads
//    as a default, and has to be dark enough to see — which fights the text
//    underneath. Many faint marks are unremovable, unccroppable, and sit
//    quietly behind the content instead of across it.
//  • A footer band naming the document as a preview and saying how to remove
//    it. This is the part that converts: it looks deliberate rather than
//    broken, and it tells the user exactly what to do about it.
//
// The wordmark colours are chosen per REGION at paint time (light over a dark
// sidebar, dark over white) so it stays legible on any template.
const WATERMARK = Object.freeze({
  text: 'CrewApply',
  footer: 'FREE PREVIEW · Generated with CrewApply · Subscribe to remove this watermark',
  opacity: 0.075,
  angle: -32,
  // Tile pitch in pt. Wide enough not to read as noise, tight enough that no
  // meaningful area of the page is left unmarked.
  stepX: 168,
  stepY: 116,
});

const generate = async (userId, resumeConfigurationId, { format = 'pdf' } = {}) => {
  const resumeConfig = await ResumeConfiguration.findOne({ _id: resumeConfigurationId, user: userId });
  if (!resumeConfig) {
    throw new AppError(AUTH_MESSAGES.RESUME_CONFIGURATION_NOT_FOUND, HTTP_STATUS.NOT_FOUND, 'NOT_FOUND');
  }

  // .lean() is deliberate here, not an optimization detail: without it,
  // careerProfile.experience[i].responsibilities is a live MongooseArray
  // still attached to its parent document's schema. pdfmake's internal list
  // preprocessor normalizes `ul` items IN PLACE (content[i] = {text: ...}),
  // which — if that array is still Mongoose-backed — re-triggers a CAST of
  // the new object back against the `responsibilities: [String]` path and
  // throws. The composer/engine must only ever see plain, fully-detached
  // data, never a live document, precisely to rule out this class of bug.
  // Entitlement is resolved HERE, from `userId` — the authenticated user on
  // the request — and never from anything the caller supplies. If this lookup
  // throws, generate() throws with it: a database hiccup must fail the render,
  // never silently fall through to an unwatermarked document.
  const [careerProfile, template, aggregated, isSubscribed] = await Promise.all([
    CareerProfile.findById(resumeConfig.careerProfile).lean(),
    ResumeTemplate.findOne({ _id: resumeConfig.templateId, isActive: true }).lean(),
    aggregation.getAggregatedProfile(userId),
    entitlementService.hasActiveSubscription(userId),
  ]);

  if (!careerProfile) {
    throw new AppError(AUTH_MESSAGES.NOT_FOUND, HTTP_STATUS.NOT_FOUND, 'NOT_FOUND');
  }
  if (!template) {
    throw new AppError(AUTH_MESSAGES.RESUME_TEMPLATE_NOT_FOUND, HTTP_STATUS.BAD_REQUEST, 'INVALID_TEMPLATE');
  }

  const content = composer.resolveContent(careerProfile, resumeConfig, aggregated);

  // Hashed HERE, before anything renders. The renderer walks structures that
  // can still reference parts of `content`, and pdfmake mutates some of what it
  // is given (its list preprocessor rewrites `ul` items in place, adding layout
  // metadata and pixel positions). Hashing afterwards captured that pollution,
  // so the stored value could never be reproduced by the staleness check and
  // every resume with bullet points showed "Out of date" forever — including
  // immediately after regenerating. buildDocumentModel now copies the array
  // too; this ordering means a future aliasing mistake still cannot corrupt the
  // hash.
  const generatedContentHash = contentHash(content, template._id);

  const documentModel = buildDocumentModel(content, template.layout);

  // Stamped onto the model AFTER the builder has run, so a template's `layout`
  // cannot reach this field — buildDocumentModel returns a fixed set of keys
  // and `watermark` is not one of them. One code path produces a PDF, and this
  // is the only place the flag is decided.
  const watermarked = !isSubscribed;
  if (watermarked) documentModel.watermark = WATERMARK;

  const buffer = await rendererRegistry.get(format).render(documentModel);

  const version = (resumeConfig.metadata.generatedDocumentIds?.length || 0) + 1;
  const filename = `${crypto.randomUUID()}.pdf`;
  const relativePath = saveBuffer(buffer, 'resumes', filename);

  // Archive only THIS resume configuration's previous generated document —
  // never another named resume's, and never an uploaded (non-generated) one.
  await Document.updateMany(
    { user: userId, source: 'generated', 'generatedFrom.resumeConfigurationId': resumeConfig._id, status: 'active' },
    { $set: { status: 'archived' } }
  );

  const doc = await Document.create({
    user: userId,
    category: 'resume',
    originalName: `${resumeConfig.title}.pdf`,
    storedName: filename,
    path: relativePath,
    mimeType: 'application/pdf',
    size: buffer.length,
    status: 'active',
    source: 'generated',
    // `watermarked` is recorded on the document itself so the state of the
    // file on disk is auditable after the fact, and so a later access-time
    // check can tell a free-tier preview from a paid copy without re-parsing
    // the PDF.
    generatedFrom: { resumeConfigurationId: resumeConfig._id, templateId: template._id, version, watermarked },
  });

  resumeConfig.metadata.lastGeneratedAt = new Date();
  resumeConfig.metadata.lastGeneratedDocumentId = doc._id;
  resumeConfig.metadata.generatedDocumentIds.push(doc._id);
  resumeConfig.metadata.contentHashAtLastGeneration = generatedContentHash;
  await resumeConfig.save();

  return doc;
};

const getHistory = async (userId, resumeConfigurationId) => {
  const resumeConfig = await ResumeConfiguration.findOne({ _id: resumeConfigurationId, user: userId }).lean();
  if (!resumeConfig) {
    throw new AppError(AUTH_MESSAGES.RESUME_CONFIGURATION_NOT_FOUND, HTTP_STATUS.NOT_FOUND, 'NOT_FOUND');
  }
  return Document.find({ _id: { $in: resumeConfig.metadata.generatedDocumentIds || [] } })
    .sort({ createdAt: -1 })
    .lean();
};

module.exports = { generate, getHistory, contentHash };
