'use strict';

const AUDIT_EVENTS = Object.freeze({
  // Registration
  REGISTER: 'REGISTER',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  VERIFICATION_EMAIL_RESENT: 'VERIFICATION_EMAIL_RESENT',

  // Authentication
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',

  // Password
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',

  // OAuth
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  GOOGLE_REGISTER: 'GOOGLE_REGISTER',

  // Security
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  SUSPICIOUS_TOKEN_REUSE: 'SUSPICIOUS_TOKEN_REUSE',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',

  // Mobile OTP
  MOBILE_OTP_SENT: 'MOBILE_OTP_SENT',
  MOBILE_OTP_VERIFIED: 'MOBILE_OTP_VERIFIED',
  MOBILE_OTP_FAILED: 'MOBILE_OTP_FAILED',
  MOBILE_OTP_EXPIRED: 'MOBILE_OTP_EXPIRED',

  // Profile
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  MARITIME_PROFILE_UPDATED: 'MARITIME_PROFILE_UPDATED',
  PROFILE_PHOTO_UPDATED: 'PROFILE_PHOTO_UPDATED',

  // Users (admin)
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',

  // Admin accounts
  ADMIN_INVITED: 'ADMIN_INVITED',
  ADMIN_INVITE_ACCEPTED: 'ADMIN_INVITE_ACCEPTED',

  // Documents
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_VIEWED_BY_ADMIN: 'DOCUMENT_VIEWED_BY_ADMIN',

  // Jobs (admin)
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  JOB_STATUS_CHANGED: 'JOB_STATUS_CHANGED',
  JOB_DELETED: 'JOB_DELETED',

  // Banners (admin)
  BANNER_CREATED: 'BANNER_CREATED',
  BANNER_UPDATED: 'BANNER_UPDATED',
  BANNER_DELETED: 'BANNER_DELETED',

  // Subscriptions & payments
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  PLAN_CREATED: 'PLAN_CREATED',
  PLAN_UPDATED: 'PLAN_UPDATED',
  PRICING_SETTING_UPDATED: 'PRICING_SETTING_UPDATED',
  CONSULTANCY_FEE_UPDATED: 'CONSULTANCY_FEE_UPDATED',
  CONSULTANCY_SCHEDULE_UPDATED: 'CONSULTANCY_SCHEDULE_UPDATED',
  CONSULTANCY_BOOKING_STATUS_CHANGED: 'CONSULTANCY_BOOKING_STATUS_CHANGED',

  // Applications
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_WITHDRAWN: 'APPLICATION_WITHDRAWN',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',

  // Document Types (admin)
  DOCUMENT_TYPE_CREATED: 'DOCUMENT_TYPE_CREATED',
  DOCUMENT_TYPE_UPDATED: 'DOCUMENT_TYPE_UPDATED',
  DOCUMENT_TYPE_DEACTIVATED: 'DOCUMENT_TYPE_DEACTIVATED',

  // Job Taxonomy — Department/Vessel Type (admin)
  JOB_TAXONOMY_CREATED: 'JOB_TAXONOMY_CREATED',
  JOB_TAXONOMY_UPDATED: 'JOB_TAXONOMY_UPDATED',
  JOB_TAXONOMY_DEACTIVATED: 'JOB_TAXONOMY_DEACTIVATED',

  // Career Profile Engine
  CAREER_PROFILE_UPDATED: 'CAREER_PROFILE_UPDATED',
  RESUME_TEMPLATE_CREATED: 'RESUME_TEMPLATE_CREATED',
  RESUME_TEMPLATE_UPDATED: 'RESUME_TEMPLATE_UPDATED',
  RESUME_TEMPLATE_DEACTIVATED: 'RESUME_TEMPLATE_DEACTIVATED',
  RESUME_CONFIGURATION_CREATED: 'RESUME_CONFIGURATION_CREATED',
  RESUME_CONFIGURATION_UPDATED: 'RESUME_CONFIGURATION_UPDATED',
  RESUME_CONFIGURATION_DELETED: 'RESUME_CONFIGURATION_DELETED',
  RESUME_GENERATED: 'RESUME_GENERATED',

  // Referrals & wallet
  REFERRAL_ATTRIBUTED: 'REFERRAL_ATTRIBUTED',
  REFERRAL_QUALIFIED: 'REFERRAL_QUALIFIED',
  REFERRAL_REWARDED: 'REFERRAL_REWARDED',
  REFERRAL_REWARD_CAPPED: 'REFERRAL_REWARD_CAPPED',
  REFERRAL_REWARD_SKIPPED: 'REFERRAL_REWARD_SKIPPED',
  REFERRAL_STATUS_CHANGED: 'REFERRAL_STATUS_CHANGED',
  REFERRAL_SETTING_UPDATED: 'REFERRAL_SETTING_UPDATED',
  WALLET_CREDITED: 'WALLET_CREDITED',
  WALLET_REDEEMED: 'WALLET_REDEEMED',
});

module.exports = { AUDIT_EVENTS };
