'use strict';

const AUDIT_EVENTS = Object.freeze({
  // Registration
  REGISTER: 'REGISTER',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  VERIFICATION_EMAIL_RESENT: 'VERIFICATION_EMAIL_RESENT',

  // Authentication
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',

  // Password
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',

  // OAuth
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  GOOGLE_REGISTER: 'GOOGLE_REGISTER',

  // Security
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  SUSPICIOUS_TOKEN_REUSE: 'SUSPICIOUS_TOKEN_REUSE',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',

  // Mobile OTP
  MOBILE_OTP_SENT: 'MOBILE_OTP_SENT',
  MOBILE_OTP_VERIFIED: 'MOBILE_OTP_VERIFIED',
  MOBILE_OTP_FAILED: 'MOBILE_OTP_FAILED',
  MOBILE_OTP_EXPIRED: 'MOBILE_OTP_EXPIRED',

  // Profile
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  MARITIME_PROFILE_UPDATED: 'MARITIME_PROFILE_UPDATED',
  PROFILE_PHOTO_UPDATED: 'PROFILE_PHOTO_UPDATED',

  // Documents
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
});

module.exports = { AUDIT_EVENTS };
